source 'https://github.com/CocoaPods/Specs.git'
plugin 'slather'

target 'NLabel', :exclusive => true do
  pod "NLabel", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NLabel", :path => "../"

  
end
