language: objective-c
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xctool -workspace Example/NLabel.xcworkspace -scheme NLabel-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
